# Generated by Django 5.0.14 on 2025-10-26 23:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("events", "0001_initial"),
        ("tenants", "0001_initial"),
        ("zones", "0003_add_row_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fiscal_series",
                    models.CharField(
                        blank=True,
                        help_text="Consecutive fiscal series number (generated on completion)",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("online", "Online Sale"),
                            ("offline", "Offline Sale"),
                            ("partial_payment", "Partial Payment"),
                        ],
                        default="online",
                        help_text="Type of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Subtotal before taxes",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total tax amount",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total transaction amount",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Transaction currency", max_length=3
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Exchange rate used for conversion",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reserved", "Reserved (Partial Payment)"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="Current transaction status",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When transaction was completed",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offline_block_id",
                    models.CharField(
                        blank=True,
                        help_text="Offline block ID for offline transactions",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Sync"),
                            ("synced", "Synced"),
                            ("conflict", "Sync Conflict"),
                        ],
                        default="synced",
                        help_text="Synchronization status for offline transactions",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional transaction notes"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional transaction metadata",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who made the purchase",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="customers.customer",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event this transaction is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="events.event",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservedTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of reserved tickets (for general admission)",
                    ),
                ),
                (
                    "reserved_until",
                    models.DateTimeField(help_text="When this reservation expires"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        help_text="Current reservation status",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seat",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reserved seat (for numbered zones)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="zones.seat",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        help_text="Zone for this reservation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="zones.zone",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="Transaction this reservation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserved_tickets",
                        to="sales.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserved Ticket",
                "verbose_name_plural": "Reserved Tickets",
                "db_table": "reserved_tickets",
                "ordering": ["reserved_until"],
            },
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("general_admission", "General Admission"),
                            ("numbered_seat", "Numbered Seat"),
                            ("table", "Table"),
                        ],
                        default="general_admission",
                        help_text="Type of ticket item",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of tickets (for general admission)"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit before taxes",
                        max_digits=10,
                    ),
                ),
                (
                    "subtotal_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Subtotal (unit_price * quantity)",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Tax rate applied (as decimal, e.g., 0.1600 for 16%)",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tax amount for this item",
                        max_digits=10,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price including taxes",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Item description", max_length=255
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional item metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seat",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific seat (for numbered zones only)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_items",
                        to="zones.seat",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="Transaction this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.transaction",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        help_text="Zone for this ticket",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction_items",
                        to="zones.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Item",
                "verbose_name_plural": "Transaction Items",
                "db_table": "transaction_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FiscalSeriesCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_series",
                    models.PositiveIntegerField(
                        default=0, help_text="Current fiscal series number"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Event for series counter (null for global tenant counter)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_counters",
                        to="events.event",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Series Counter",
                "verbose_name_plural": "Fiscal Series Counters",
                "db_table": "fiscal_series_counters",
                "indexes": [
                    models.Index(
                        fields=["tenant", "event"],
                        name="fiscal_seri_tenant__a57e44_idx",
                    )
                ],
                "unique_together": {("tenant", "event")},
            },
        ),
        migrations.CreateModel(
            name="OfflineBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "block_id",
                    models.CharField(
                        help_text="Unique block identifier", max_length=50, unique=True
                    ),
                ),
                (
                    "start_series",
                    models.PositiveIntegerField(
                        help_text="Starting series number for this block"
                    ),
                ),
                (
                    "end_series",
                    models.PositiveIntegerField(
                        help_text="Ending series number for this block"
                    ),
                ),
                (
                    "current_series",
                    models.PositiveIntegerField(
                        help_text="Current series number being used"
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        help_text="Terminal or user this block is assigned to",
                        max_length=255,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this block expires (8 hours from assignment)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("synced", "Synced"),
                        ],
                        default="assigned",
                        help_text="Current block status",
                        max_length=10,
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, help_text="When this block was synced", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional block metadata"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Block",
                "verbose_name_plural": "Offline Blocks",
                "db_table": "offline_blocks",
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="offline_blo_tenant__dcf4d3_idx",
                    ),
                    models.Index(
                        fields=["block_id"], name="offline_blo_block_i_951f3b_idx"
                    ),
                    models.Index(
                        fields=["assigned_to"], name="offline_blo_assigne_7a2c1a_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="offline_blo_expires_e89a61_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["tenant", "event", "status"],
                name="transaction_tenant__179a04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["tenant", "customer"], name="transaction_tenant__bca4dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["fiscal_series"], name="transaction_fiscal__9fea01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["created_at"], name="transaction_created_5c02ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["offline_block_id"], name="transaction_offline_116f43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservedticket",
            index=models.Index(
                fields=["tenant", "status", "reserved_until"],
                name="reserved_ti_tenant__a7177b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservedticket",
            index=models.Index(
                fields=["transaction"], name="reserved_ti_transac_70f6d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservedticket",
            index=models.Index(fields=["seat"], name="reserved_ti_seat_id_c5dcc7_idx"),
        ),
        migrations.AddIndex(
            model_name="reservedticket",
            index=models.Index(fields=["zone"], name="reserved_ti_zone_id_f00443_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionitem",
            index=models.Index(
                fields=["tenant", "transaction"], name="transaction_tenant__59ced7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionitem",
            index=models.Index(fields=["zone"], name="transaction_zone_id_ee7ca5_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionitem",
            index=models.Index(fields=["seat"], name="transaction_seat_id_42490d_idx"),
        ),
    ]
