# Generated by Django 5.0.14 on 2025-11-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="processing_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When background processing (notifications, tickets) was completed",
                null=True,
            ),
        ),
    ]
