# Generated by Django 5.0.14 on 2025-11-01 23:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_add_processing_completed_at"),
        ("tenants", "0002_add_performance_indexes"),
        ("zones", "0004_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItemLock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="Django session key for anonymous users",
                        max_length=40,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of tickets locked (for general admission)",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the lock was created"
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="When the lock expires")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("released", "Released"),
                            ("converted", "Converted to Sale"),
                        ],
                        default="active",
                        help_text="Current lock status",
                        max_length=10,
                    ),
                ),
                (
                    "price_at_lock",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price when item was locked",
                        max_digits=10,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional lock metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seat",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific seat (for numbered zones only)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_locks",
                        to="zones.seat",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User if authenticated",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        help_text="Zone containing the locked item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_locks",
                        to="zones.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item Lock",
                "verbose_name_plural": "Cart Item Locks",
                "db_table": "cart_item_locks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "expires_at"],
                        name="cart_item_l_tenant__1a4aa3_idx",
                    ),
                    models.Index(
                        fields=["session_key", "status"],
                        name="cart_item_l_session_314d40_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="cart_item_l_user_id_8dcae4_idx"
                    ),
                    models.Index(
                        fields=["zone", "status"], name="cart_item_l_zone_id_d97db0_idx"
                    ),
                    models.Index(
                        fields=["seat", "status"], name="cart_item_l_seat_id_503484_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="cartitemlock",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="cart_lock_positive_quantity"
            ),
        ),
    ]
