# Generated by Django 5.0.14 on 2025-10-26 03:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Event name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Event description"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("general_assignment", "General Assignment Event"),
                            ("numbered_seat", "Numbered Seat Event"),
                            ("mixed", "Mixed Event (Both Types)"),
                        ],
                        default="general_assignment",
                        help_text="Type of event seating",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Event start date and time"),
                ),
                ("end_date", models.DateTimeField(help_text="Event end date and time")),
                (
                    "sales_start_date",
                    models.DateTimeField(
                        blank=True, help_text="When ticket sales begin", null=True
                    ),
                ),
                (
                    "sales_end_date",
                    models.DateTimeField(
                        blank=True, help_text="When ticket sales end", null=True
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        default="USD",
                        help_text="Base currency for event pricing",
                        max_length=3,
                    ),
                ),
                (
                    "currency_conversion_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Conversion rate from USD to local currency",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Current event status",
                        max_length=10,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event-specific configuration settings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "partial_payments_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether partial payments are allowed for this event",
                    ),
                ),
                (
                    "installment_plans_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether installment payment plans are available",
                    ),
                ),
                (
                    "flexible_payments_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether flexible payment plans are available",
                    ),
                ),
                (
                    "max_installments",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum number of installments allowed"
                    ),
                ),
                (
                    "min_down_payment_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Minimum down payment percentage required",
                        max_digits=5,
                    ),
                ),
                (
                    "payment_plan_expiry_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Days until payment plan expires"
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether notifications are enabled for this event",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Send email notifications"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, help_text="Send SMS notifications"
                    ),
                ),
                (
                    "whatsapp_notifications",
                    models.BooleanField(
                        default=False, help_text="Send WhatsApp notifications"
                    ),
                ),
                (
                    "send_purchase_confirmation",
                    models.BooleanField(
                        default=True,
                        help_text="Send confirmation when purchase is completed",
                    ),
                ),
                (
                    "send_payment_reminders",
                    models.BooleanField(
                        default=True, help_text="Send reminders for pending payments"
                    ),
                ),
                (
                    "send_event_reminders",
                    models.BooleanField(
                        default=True, help_text="Send reminders before event starts"
                    ),
                ),
                (
                    "event_reminder_days",
                    models.PositiveIntegerField(
                        default=1, help_text="Days before event to send reminder"
                    ),
                ),
                (
                    "digital_tickets_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether digital tickets are generated"
                    ),
                ),
                (
                    "qr_codes_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether QR codes are included in tickets",
                    ),
                ),
                (
                    "pdf_tickets_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether PDF tickets are generated"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event-specific configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        help_text="Event this configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_configuration",
                        to="events.event",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Configuration",
                "verbose_name_plural": "Event Configurations",
                "db_table": "event_configurations",
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Venue name", max_length=255)),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Physical address of the venue"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City where venue is located",
                        max_length=100,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="State/Province", max_length=100
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Venezuela", help_text="Country", max_length=100
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, help_text="Postal/ZIP code", max_length=20
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum venue capacity", null=True
                    ),
                ),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Venue"),
                            ("virtual", "Virtual Venue"),
                            ("hybrid", "Hybrid Venue"),
                        ],
                        default="physical",
                        help_text="Type of venue",
                        max_length=50,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Venue contact phone", max_length=20
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Venue contact email", max_length=254
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Venue-specific configuration settings",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether venue is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue",
                "verbose_name_plural": "Venues",
                "db_table": "venues",
                "ordering": ["name"],
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                help_text="Venue where event takes place",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="events.venue",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("tenant", "name", "start_date")},
        ),
    ]
