# Generated by Django 5.0.14 on 2025-11-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("tenants", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["tenant", "status"], name="events_tenant__def9dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["tenant", "start_date"], name="events_tenant__d138d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["tenant", "event_type"], name="events_tenant__1d1947_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["venue", "start_date"], name="events_venue_i_90e1b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_date", "end_date"], name="events_start_d_92ba55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["sales_start_date", "sales_end_date"],
                name="events_sales_s_e52726_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["created_at"], name="events_created_9e2206_idx"),
        ),
        migrations.AddIndex(
            model_name="eventconfiguration",
            index=models.Index(
                fields=["tenant", "partial_payments_enabled"],
                name="event_confi_tenant__7a6b43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventconfiguration",
            index=models.Index(
                fields=["tenant", "notifications_enabled"],
                name="event_confi_tenant__535f29_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["tenant", "is_active"], name="venues_tenant__122c0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["tenant", "venue_type"], name="venues_tenant__d543da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(fields=["city", "state"], name="venues_city_76f08d_idx"),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(fields=["created_at"], name="venues_created_947a43_idx"),
        ),
    ]
