# Generated by Django 5.0.14 on 2025-11-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventconfiguration",
            name="bank_transfer_enabled",
            field=models.BooleanField(
                default=True, help_text="Accept bank transfer payments"
            ),
        ),
        migrations.AddField(
            model_name="eventconfiguration",
            name="cash_enabled",
            field=models.BooleanField(default=True, help_text="Accept cash payments"),
        ),
        migrations.AddField(
            model_name="eventconfiguration",
            name="credit_card_enabled",
            field=models.BooleanField(
                default=True, help_text="Accept credit card payments"
            ),
        ),
        migrations.AddField(
            model_name="eventconfiguration",
            name="debit_card_enabled",
            field=models.BooleanField(
                default=True, help_text="Accept debit card payments"
            ),
        ),
        migrations.AddField(
            model_name="eventconfiguration",
            name="mobile_payment_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Accept mobile payment (Pago Móvil, Zelle, etc.)",
            ),
        ),
    ]
