# Generated by Django 5.0.14 on 2025-11-01 17:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("sales", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("X", "X-Report (Daily Summary)"),
                            ("Z", "Z-Report (Fiscal Closure)"),
                        ],
                        max_length=1,
                    ),
                ),
                ("report_number", models.BigIntegerField()),
                ("fiscal_date", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("total_transactions", models.IntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "cash_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "card_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "transfer_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "other_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("first_series", models.BigIntegerField(blank=True, null=True)),
                ("last_series", models.BigIntegerField(blank=True, null=True)),
                ("report_data", models.JSONField(default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_reports",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Report",
                "verbose_name_plural": "Fiscal Reports",
                "db_table": "fiscal_report",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="FiscalDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fiscal_date", models.DateField()),
                ("is_closed", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_days",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "z_report",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiscal_day",
                        to="fiscal.fiscalreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Day",
                "verbose_name_plural": "Fiscal Days",
                "db_table": "fiscal_day",
                "ordering": ["-fiscal_date", "user"],
            },
        ),
        migrations.CreateModel(
            name="FiscalSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("series_number", models.BigIntegerField()),
                ("issued_at", models.DateTimeField()),
                ("is_voided", models.BooleanField(default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_fiscal_series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_series",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_series_record",
                        to="sales.transaction",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voided_fiscal_series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Series",
                "verbose_name_plural": "Fiscal Series",
                "db_table": "fiscal_series",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VOID", "Void"),
                            ("CLOSE", "Close"),
                            ("REPORT", "Report Generation"),
                        ],
                        max_length=10,
                    ),
                ),
                ("object_type", models.CharField(max_length=50)),
                ("object_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="fiscal.fiscalseries",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FiscalSeriesCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_series", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_series_counter",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Series Counter",
                "verbose_name_plural": "Fiscal Series Counters",
                "db_table": "fiscal_series_counter",
            },
        ),
        migrations.CreateModel(
            name="TaxConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed Amount"),
                            ("COMPOUND", "Compound Tax"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("TENANT", "Tenant Level"), ("EVENT", "Event Level")],
                        max_length=10,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Tax rate (percentage as decimal, e.g., 0.16 for 16%)",
                        max_digits=8,
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed tax amount (for FIXED tax type)",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tax_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_configurations",
                        to="events.event",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_configurations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Configuration",
                "verbose_name_plural": "Tax Configurations",
                "db_table": "tax_configuration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxCalculationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_calculation_history",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_calculations",
                        to="sales.transaction",
                    ),
                ),
                (
                    "tax_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculation_history",
                        to="fiscal.taxconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Calculation History",
                "verbose_name_plural": "Tax Calculation History",
                "db_table": "tax_calculation_history",
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="fiscalreport",
            index=models.Index(
                fields=["tenant", "report_type", "fiscal_date"],
                name="fiscal_repo_tenant__7366c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalreport",
            index=models.Index(
                fields=["tenant", "user", "fiscal_date"],
                name="fiscal_repo_tenant__1e30d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalreport",
            index=models.Index(
                fields=["generated_at"], name="fiscal_repo_generat_3a164a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fiscalreport",
            unique_together={("tenant", "report_type", "report_number")},
        ),
        migrations.AddIndex(
            model_name="fiscalday",
            index=models.Index(
                fields=["tenant", "user", "fiscal_date"],
                name="fiscal_day_tenant__dcf554_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalday",
            index=models.Index(
                fields=["tenant", "fiscal_date", "is_closed"],
                name="fiscal_day_tenant__93f11a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fiscalday",
            unique_together={("tenant", "user", "fiscal_date")},
        ),
        migrations.AddIndex(
            model_name="fiscalseries",
            index=models.Index(
                fields=["tenant", "series_number"],
                name="fiscal_seri_tenant__703f4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalseries",
            index=models.Index(
                fields=["tenant", "issued_at"], name="fiscal_seri_tenant__bfa4e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalseries",
            index=models.Index(
                fields=["transaction"], name="fiscal_seri_transac_133626_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fiscalseries",
            unique_together={("tenant", "series_number")},
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "timestamp"], name="audit_log_tenant__ae62a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_log_user_id_835db7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["object_type", "object_id"], name="audit_log_object__8ccc11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["fiscal_series"], name="audit_log_fiscal__21b992_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action_type", "timestamp"], name="audit_log_action__ebbe27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxconfiguration",
            index=models.Index(
                fields=["tenant", "scope", "is_active"],
                name="tax_configu_tenant__42d2e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxconfiguration",
            index=models.Index(
                fields=["event", "is_active"], name="tax_configu_event_i_b33875_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxconfiguration",
            index=models.Index(
                fields=["effective_from", "effective_until"],
                name="tax_configu_effecti_e4911f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxcalculationhistory",
            index=models.Index(
                fields=["tenant", "calculated_at"],
                name="tax_calcula_tenant__9b8c76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxcalculationhistory",
            index=models.Index(
                fields=["transaction"], name="tax_calcula_transac_21174f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxcalculationhistory",
            index=models.Index(
                fields=["tax_configuration"], name="tax_calcula_tax_con_2cc1a0_idx"
            ),
        ),
    ]
