# Generated by Django 5.0.14 on 2025-11-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxconfiguration",
            name="effective_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
