# Generated by Django 5.0.14 on 2025-10-26 17:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.PositiveIntegerField(help_text="Row number")),
                (
                    "seat_number",
                    models.PositiveIntegerField(help_text="Seat number within the row"),
                ),
                (
                    "price_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Price modifier percentage (e.g., 10.00 for 10% increase)",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                            ("blocked", "Blocked"),
                        ],
                        default="available",
                        help_text="Current seat status",
                        max_length=10,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Seat-specific configuration settings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat",
                "verbose_name_plural": "Seats",
                "db_table": "seats",
                "ordering": ["row_number", "seat_number"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Table name or number", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Table description"),
                ),
                (
                    "sale_mode",
                    models.CharField(
                        choices=[
                            ("complete_only", "Complete Table Only"),
                            ("individual_allowed", "Individual Seats Allowed"),
                        ],
                        default="individual_allowed",
                        help_text="How this table can be sold",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("sold_out", "Sold Out"),
                        ],
                        default="active",
                        help_text="Current table status",
                        max_length=10,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying tables"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Table-specific configuration settings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "db_table": "tables",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TableSeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Position of seat within the table"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seat",
                    models.ForeignKey(
                        help_text="Seat that belongs to the table",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_memberships",
                        to="zones.seat",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="Table this relationship belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_seats",
                        to="zones.table",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table Seat",
                "verbose_name_plural": "Table Seats",
                "db_table": "table_seats",
                "ordering": ["position"],
                "unique_together": {("table", "seat")},
            },
        ),
        migrations.AddField(
            model_name="seat",
            name="tables",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tables this seat belongs to",
                related_name="seats",
                through="zones.TableSeat",
                to="zones.table",
            ),
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Zone name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Zone description"),
                ),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("general", "General Zone"),
                            ("numbered", "Numbered Zone"),
                        ],
                        default="general",
                        help_text="Type of zone (general or numbered)",
                        max_length=10,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum capacity for this zone"
                    ),
                ),
                (
                    "rows",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of rows (for numbered zones only)",
                        null=True,
                    ),
                ),
                (
                    "seats_per_row",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of seats per row (for numbered zones only)",
                        null=True,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price for tickets in this zone",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("sold_out", "Sold Out"),
                        ],
                        default="active",
                        help_text="Current zone status",
                        max_length=10,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying zones"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Zone-specific configuration settings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event this zone belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="events.event",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "db_table": "zones",
                "ordering": ["display_order", "name"],
                "unique_together": {("event", "name")},
            },
        ),
        migrations.AddField(
            model_name="table",
            name="zone",
            field=models.ForeignKey(
                help_text="Zone this table belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="zones.zone",
            ),
        ),
        migrations.AddField(
            model_name="seat",
            name="zone",
            field=models.ForeignKey(
                help_text="Zone this seat belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="zones.zone",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("zone", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("zone", "row_number", "seat_number")},
        ),
    ]
