# Generated by Django 5.0.14 on 2025-10-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="map_height",
            field=models.FloatField(
                blank=True,
                default=80.0,
                help_text="Height of zone on venue map (pixels or percentage)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="map_rotation",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Rotation angle in degrees",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="map_width",
            field=models.FloatField(
                blank=True,
                default=100.0,
                help_text="Width of zone on venue map (pixels or percentage)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="map_x",
            field=models.FloatField(
                blank=True,
                help_text="X coordinate on venue map (pixels or percentage)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="map_y",
            field=models.FloatField(
                blank=True,
                help_text="Y coordinate on venue map (pixels or percentage)",
                null=True,
            ),
        ),
    ]
