# Generated by Django 5.0.14 on 2025-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0002_add_zone_map_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="row_configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom seats per row configuration: {'1': 10, '2': 9, '3': 8, ...}",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="seats_per_row",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Default number of seats per row (for numbered zones only)",
                null=True,
            ),
        ),
    ]
