# Generated by Django 5.0.14 on 2025-11-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_add_performance_indexes"),
        ("tenants", "0002_add_performance_indexes"),
        ("zones", "0003_add_row_configuration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(
                fields=["tenant", "zone", "status"], name="seats_tenant__92976c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(
                fields=["zone", "status"], name="seats_zone_id_c27b58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(
                fields=["zone", "row_number"], name="seats_zone_id_4cec11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(fields=["status"], name="seats_status_1a0561_idx"),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["tenant", "zone", "status"], name="tables_tenant__ff33e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["zone", "status"], name="tables_zone_id_eb8c8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(fields=["status"], name="tables_status_cabc1b_idx"),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["display_order"], name="tables_display_89d926_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tableseat",
            index=models.Index(
                fields=["tenant", "table"], name="table_seats_tenant__272f75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tableseat",
            index=models.Index(
                fields=["table", "position"], name="table_seats_table_i_9baac6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["tenant", "event", "status"], name="zones_tenant__6b174d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["tenant", "zone_type"], name="zones_tenant__8720cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["event", "zone_type"], name="zones_event_i_bef3b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(fields=["status"], name="zones_status_b6ee92_idx"),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["display_order"], name="zones_display_57b8b1_idx"
            ),
        ),
    ]
