# Generated by Django 5.0.14 on 2025-11-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="map_color",
            field=models.CharField(
                blank=True,
                help_text="Hex color code used to render this zone on the map (e.g. #3B5BDB)",
                max_length=7,
            ),
        ),
    ]
