# Generated by Django 5.0.14 on 2025-10-26 23:06

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
import venezuelan_pos.apps.customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Customer's first name", max_length=100),
                ),
                (
                    "surname",
                    models.CharField(help_text="Customer's last name", max_length=100),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Customer's phone number (Venezuelan format preferred)",
                        max_length=128,
                        null=True,
                        region="VE",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Customer's email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "identification",
                    models.CharField(
                        blank=True,
                        help_text="Venezuelan cédula (format: V-12345678 or E-12345678)",
                        max_length=15,
                        null=True,
                        validators=[
                            venezuelan_pos.apps.customers.models.validate_venezuelan_cedula
                        ],
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Customer's date of birth", null=True
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Customer's address"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the customer"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether customer is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
                "ordering": ["surname", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, help_text="Allow email communications"
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=True, help_text="Allow SMS communications"
                    ),
                ),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=True, help_text="Allow WhatsApp communications"
                    ),
                ),
                (
                    "phone_enabled",
                    models.BooleanField(
                        default=False, help_text="Allow phone call communications"
                    ),
                ),
                (
                    "purchase_confirmations",
                    models.BooleanField(
                        default=True,
                        help_text="Receive purchase confirmation notifications",
                    ),
                ),
                (
                    "payment_reminders",
                    models.BooleanField(
                        default=True, help_text="Receive payment reminder notifications"
                    ),
                ),
                (
                    "event_reminders",
                    models.BooleanField(
                        default=True, help_text="Receive event reminder notifications"
                    ),
                ),
                (
                    "promotional_messages",
                    models.BooleanField(
                        default=False, help_text="Receive promotional messages"
                    ),
                ),
                (
                    "system_updates",
                    models.BooleanField(
                        default=True, help_text="Receive system update notifications"
                    ),
                ),
                (
                    "preferred_contact_time_start",
                    models.TimeField(
                        default="09:00",
                        help_text="Preferred start time for communications",
                    ),
                ),
                (
                    "preferred_contact_time_end",
                    models.TimeField(
                        default="18:00",
                        help_text="Preferred end time for communications",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("es", "Español"), ("en", "English")],
                        default="es",
                        help_text="Preferred language for communications",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        help_text="Customer these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Preferences",
                "verbose_name_plural": "Customer Preferences",
                "db_table": "customer_preferences",
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "surname", "name"],
                name="customers_tenant__5a79d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "phone"], name="customers_tenant__a2831a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "email"], name="customers_tenant__074712_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "identification"], name="customers_tenant__729a21_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identification__isnull", False)),
                fields=("tenant", "identification"),
                name="unique_identification_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("tenant", "email"),
                name="unique_email_per_tenant",
            ),
        ),
    ]
