# Generated by Django 5.0.14 on 2025-10-26 21:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("tenants", "0001_initial"),
        ("zones", "0003_add_row_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Price stage name (e.g., 'Early Bird', 'Regular', 'Last Minute')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this pricing stage"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="When this pricing stage becomes active"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="When this pricing stage ends"),
                ),
                (
                    "percentage_markup",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage markup over base price (e.g., 15.00 for 15% increase)",
                        max_digits=5,
                    ),
                ),
                (
                    "stage_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of this stage in the pricing sequence",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this price stage is active"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional stage-specific configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event this price stage belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_stages",
                        to="events.event",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Stage",
                "verbose_name_plural": "Price Stages",
                "db_table": "price_stages",
                "ordering": ["stage_order", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="RowPricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(help_text="Row number within the zone"),
                ),
                (
                    "percentage_markup",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage markup over zone base price (e.g., 25.00 for 25% increase)",
                        max_digits=5,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name for this row pricing (e.g., 'VIP Row', 'Premium')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this row pricing"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this row pricing is active"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional row-specific pricing configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        help_text="Zone this row pricing belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_pricing",
                        to="zones.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Row Pricing",
                "verbose_name_plural": "Row Pricing",
                "db_table": "row_pricing",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("zone_base", "Zone Base Price"),
                            ("stage_markup", "Price Stage Markup"),
                            ("row_markup", "Row Pricing Markup"),
                            ("final_calculated", "Final Calculated Price"),
                        ],
                        help_text="Type of price being recorded",
                        max_length=20,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price used in calculation",
                        max_digits=10,
                    ),
                ),
                (
                    "markup_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Markup percentage applied",
                        max_digits=5,
                    ),
                ),
                (
                    "markup_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calculated markup amount",
                        max_digits=10,
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final calculated price",
                        max_digits=10,
                    ),
                ),
                (
                    "calculation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this price calculation was performed",
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        blank=True, help_text="Row number (if applicable)", null=True
                    ),
                ),
                (
                    "seat_number",
                    models.PositiveIntegerField(
                        blank=True, help_text="Seat number (if applicable)", null=True
                    ),
                ),
                (
                    "calculation_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed calculation breakdown",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event this price history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="events.event",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zone this price history belongs to (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="zones.zone",
                    ),
                ),
                (
                    "price_stage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Price stage used in calculation (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="pricing.pricestage",
                    ),
                ),
                (
                    "row_pricing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Row pricing used in calculation (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="pricing.rowpricing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price History",
                "db_table": "price_history",
                "ordering": ["-calculation_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pricestage",
            index=models.Index(
                fields=["event", "start_date", "end_date"],
                name="price_stage_event_i_e2989b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricestage",
            index=models.Index(
                fields=["start_date", "end_date"], name="price_stage_start_d_3b9c40_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricestage",
            unique_together={("event", "name")},
        ),
        migrations.AddIndex(
            model_name="rowpricing",
            index=models.Index(
                fields=["zone", "row_number"], name="row_pricing_zone_id_3c3b07_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rowpricing",
            unique_together={("zone", "row_number")},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["event", "calculation_date"],
                name="price_histo_event_i_d3c8ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["zone", "calculation_date"],
                name="price_histo_zone_id_ffac5d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["price_type", "calculation_date"],
                name="price_histo_price_t_6f70a3_idx",
            ),
        ),
    ]
