# Generated by Django 5.0.14 on 2025-10-31 04:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("pricing", "0001_initial"),
        ("tenants", "0001_initial"),
        ("zones", "0003_add_row_configuration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricestage",
            name="percentage_markup",
        ),
        migrations.AddField(
            model_name="pricestage",
            name="auto_transition",
            field=models.BooleanField(
                default=True,
                help_text="Whether to automatically transition when date expires or quantity reached",
            ),
        ),
        migrations.AddField(
            model_name="pricestage",
            name="modifier_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("fixed_amount", "Fixed Amount"),
                ],
                default="percentage",
                help_text="Type of price modifier (percentage or fixed amount)",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="pricestage",
            name="modifier_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Modifier value (percentage like 15.00 for 15% or fixed amount like 25.00)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="pricestage",
            name="quantity_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum tickets that can be sold at this stage before auto-transition",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricestage",
            name="scope",
            field=models.CharField(
                choices=[("event", "Event-wide"), ("zone", "Zone-specific")],
                default="event",
                help_text="Whether this stage applies event-wide or to specific zones",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pricestage",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Zone this stage applies to (null for event-wide stages)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_stages",
                to="zones.zone",
            ),
        ),
        migrations.CreateModel(
            name="StageSales",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sales_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date of sales activity",
                    ),
                ),
                (
                    "tickets_sold",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of tickets sold on this date"
                    ),
                ),
                (
                    "revenue_generated",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Revenue generated on this date",
                        max_digits=12,
                    ),
                ),
                (
                    "cumulative_tickets_sold",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total tickets sold for this stage up to this date",
                    ),
                ),
                (
                    "cumulative_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total revenue for this stage up to this date",
                        max_digits=12,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stage",
                    models.ForeignKey(
                        help_text="Price stage this sales record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_sales",
                        to="pricing.pricestage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zone this sales record applies to (null for event-wide stages)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_sales",
                        to="zones.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage Sales",
                "verbose_name_plural": "Stage Sales",
                "db_table": "stage_sales",
                "ordering": ["-sales_date"],
                "indexes": [
                    models.Index(
                        fields=["stage", "sales_date"],
                        name="stage_sales_stage_i_e51224_idx",
                    ),
                    models.Index(
                        fields=["zone", "sales_date"],
                        name="stage_sales_zone_id_1faa26_idx",
                    ),
                    models.Index(
                        fields=["sales_date"], name="stage_sales_sales_d_6ee0c4_idx"
                    ),
                ],
                "unique_together": {("stage", "zone", "sales_date")},
            },
        ),
        migrations.CreateModel(
            name="StageTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger_reason",
                    models.CharField(
                        choices=[
                            ("date_expired", "Date Expired"),
                            ("quantity_reached", "Quantity Limit Reached"),
                            ("manual", "Manual Transition"),
                        ],
                        help_text="What triggered this transition",
                        max_length=20,
                    ),
                ),
                (
                    "sold_quantity",
                    models.PositiveIntegerField(
                        help_text="Number of tickets sold when transition occurred"
                    ),
                ),
                (
                    "transition_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the transition occurred",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional transition metadata and context",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event this transition belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_transitions",
                        to="events.event",
                    ),
                ),
                (
                    "stage_from",
                    models.ForeignKey(
                        help_text="Stage transitioning from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_from",
                        to="pricing.pricestage",
                    ),
                ),
                (
                    "stage_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Stage transitioning to (null if no next stage)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_to",
                        to="pricing.pricestage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zone this transition applies to (null for event-wide)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_transitions",
                        to="zones.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage Transition",
                "verbose_name_plural": "Stage Transitions",
                "db_table": "stage_transitions",
                "ordering": ["-transition_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "transition_at"],
                        name="stage_trans_event_i_32b1d2_idx",
                    ),
                    models.Index(
                        fields=["zone", "transition_at"],
                        name="stage_trans_zone_id_c516be_idx",
                    ),
                    models.Index(
                        fields=["stage_from", "transition_at"],
                        name="stage_trans_stage_f_4867cb_idx",
                    ),
                ],
            },
        ),
    ]
