# Generated by Django 5.0.14 on 2025-11-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_add_performance_indexes"),
        ("pricing", "0002_add_hybrid_pricing_system"),
        ("tenants", "0002_add_performance_indexes"),
        ("zones", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["tenant", "event", "calculation_date"],
                name="price_histo_tenant__69efea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["tenant", "zone", "calculation_date"],
                name="price_histo_tenant__04df02_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricestage",
            index=models.Index(
                fields=["tenant", "event", "is_active"],
                name="price_stage_tenant__f78ff7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricestage",
            index=models.Index(
                fields=["tenant", "zone", "is_active"],
                name="price_stage_tenant__a392f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricestage",
            index=models.Index(
                fields=["scope", "is_active"], name="price_stage_scope_a15110_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricestage",
            index=models.Index(
                fields=["stage_order"], name="price_stage_stage_o_123eea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rowpricing",
            index=models.Index(
                fields=["tenant", "zone", "is_active"],
                name="row_pricing_tenant__8d5a25_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rowpricing",
            index=models.Index(
                fields=["is_active"], name="row_pricing_is_acti_38f508_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stagesales",
            index=models.Index(
                fields=["tenant", "stage", "sales_date"],
                name="stage_sales_tenant__ae5955_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stagesales",
            index=models.Index(
                fields=["tenant", "zone", "sales_date"],
                name="stage_sales_tenant__7708e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stagetransition",
            index=models.Index(
                fields=["tenant", "event", "transition_at"],
                name="stage_trans_tenant__ccbe9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stagetransition",
            index=models.Index(
                fields=["tenant", "zone", "transition_at"],
                name="stage_trans_tenant__53aee1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stagetransition",
            index=models.Index(
                fields=["trigger_reason"], name="stage_trans_trigger_938fd4_idx"
            ),
        ),
    ]
