# Generated by Django 5.0.14 on 2025-11-01 18:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("tenants", "0001_initial"),
        ("zones", "0003_add_row_configuration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OccupancyAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Analysis name or title", max_length=255
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("zone", "Zone Analysis"),
                            ("event", "Event Analysis"),
                            ("comparative", "Comparative Analysis"),
                        ],
                        default="zone",
                        help_text="Type of analysis",
                        max_length=15,
                    ),
                ),
                (
                    "total_capacity",
                    models.PositiveIntegerField(
                        default=0, help_text="Total capacity analyzed"
                    ),
                ),
                (
                    "sold_tickets",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of tickets sold"
                    ),
                ),
                (
                    "fill_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fill rate percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "sales_velocity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sales velocity (tickets per day)",
                        max_digits=8,
                    ),
                ),
                (
                    "heat_map_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Heat map data for visualization",
                    ),
                ),
                (
                    "performance_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional performance metrics and rankings",
                    ),
                ),
                (
                    "analysis_start",
                    models.DateTimeField(
                        blank=True, help_text="Start of analysis period", null=True
                    ),
                ),
                (
                    "analysis_end",
                    models.DateTimeField(
                        blank=True, help_text="End of analysis period", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Event for this analysis (null for cross-event analysis)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupancy_analyses",
                        to="events.event",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who generated this analysis",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zone for this analysis (null for event-wide analysis)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupancy_analyses",
                        to="zones.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occupancy Analysis",
                "verbose_name_plural": "Occupancy Analyses",
                "db_table": "occupancy_analyses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "analysis_type"],
                        name="occupancy_a_tenant__715a2b_idx",
                    ),
                    models.Index(
                        fields=["event", "zone"], name="occupancy_a_event_i_0989e1_idx"
                    ),
                    models.Index(
                        fields=["generated_by"], name="occupancy_a_generat_05f986_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="occupancy_a_created_2726dd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Schedule name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Schedule description"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Report"),
                            ("weekly", "Weekly Report"),
                            ("monthly", "Monthly Report"),
                            ("custom", "Custom Period Report"),
                            ("event", "Event Report"),
                            ("zone", "Zone Report"),
                            ("operator", "Operator Report"),
                        ],
                        help_text="Type of report to generate",
                        max_length=20,
                    ),
                ),
                (
                    "report_filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default filters for generated reports",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        help_text="How often to generate reports",
                        max_length=15,
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(help_text="When to generate the next report"),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the last report was generated",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        help_text="Current schedule status",
                        max_length=10,
                    ),
                ),
                (
                    "email_recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Email addresses to send reports to",
                    ),
                ),
                (
                    "export_formats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Formats to export reports in",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this schedule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Schedule",
                "verbose_name_plural": "Report Schedules",
                "db_table": "report_schedules",
                "ordering": ["next_run"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "next_run"],
                        name="report_sche_tenant__cce78b_idx",
                    ),
                    models.Index(
                        fields=["frequency"], name="report_sche_frequen_825450_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="report_sche_created_5e3dad_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Report name or title", max_length=255),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Report"),
                            ("weekly", "Weekly Report"),
                            ("monthly", "Monthly Report"),
                            ("custom", "Custom Period Report"),
                            ("event", "Event Report"),
                            ("zone", "Zone Report"),
                            ("operator", "Operator Report"),
                        ],
                        help_text="Type of report",
                        max_length=20,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filters applied to generate this report",
                    ),
                ),
                (
                    "total_transactions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of transactions"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total revenue amount",
                        max_digits=12,
                    ),
                ),
                (
                    "total_tickets",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of tickets sold"
                    ),
                ),
                (
                    "average_ticket_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average price per ticket",
                        max_digits=10,
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True, help_text="Start of report period", null=True
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True, help_text="End of report period", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        help_text="Current report status",
                        max_length=15,
                    ),
                ),
                (
                    "export_formats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Available export formats for this report",
                    ),
                ),
                (
                    "detailed_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed report data (breakdowns, charts data, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When report generation was completed",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who generated this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Report",
                "verbose_name_plural": "Sales Reports",
                "db_table": "sales_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "report_type", "status"],
                        name="sales_repor_tenant__3a5121_idx",
                    ),
                    models.Index(
                        fields=["tenant", "period_start", "period_end"],
                        name="sales_repor_tenant__fac452_idx",
                    ),
                    models.Index(
                        fields=["generated_by"], name="sales_repor_generat_52eb33_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="sales_repor_created_827eb8_idx"
                    ),
                ],
            },
        ),
    ]
