# Generated by Django 5.0.14 on 2025-11-01 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("events", "0001_initial"),
        ("sales", "0001_initial"),
        ("tenants", "0001_initial"),
        ("zones", "0003_add_row_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        help_text="Unique ticket number", max_length=50, unique=True
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Sequence number for multiple tickets from same item",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("general_admission", "General Admission"),
                            ("numbered_seat", "Numbered Seat"),
                            ("multi_entry", "Multi Entry"),
                        ],
                        default="general_admission",
                        help_text="Type of ticket",
                        max_length=20,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original unit price for this ticket",
                        max_digits=10,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for this individual ticket",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Currency for pricing", max_length=3
                    ),
                ),
                (
                    "qr_code_data",
                    models.TextField(
                        blank=True, help_text="Encrypted QR code data for validation"
                    ),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True,
                        help_text="Generated QR code image",
                        null=True,
                        upload_to="tickets/qr_codes/",
                    ),
                ),
                (
                    "validation_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash for ticket validation",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="active",
                        help_text="Current ticket status",
                        max_length=10,
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times ticket has been used"
                    ),
                ),
                (
                    "max_usage_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of times ticket can be used",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="When ticket becomes valid (defaults to event start)",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="When ticket expires (defaults to event end)",
                        null=True,
                    ),
                ),
                (
                    "first_used_at",
                    models.DateTimeField(
                        blank=True, help_text="When ticket was first used", null=True
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="When ticket was last used", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional ticket metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who owns this ticket",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_tickets",
                        to="customers.customer",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event this ticket is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_tickets",
                        to="events.event",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific seat (for numbered tickets only)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_tickets",
                        to="zones.seat",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="Transaction this ticket belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_tickets",
                        to="sales.transaction",
                    ),
                ),
                (
                    "transaction_item",
                    models.ForeignKey(
                        help_text="Specific transaction item this ticket represents",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_tickets",
                        to="sales.transactionitem",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        help_text="Zone for this ticket",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_tickets",
                        to="zones.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digital Ticket",
                "verbose_name_plural": "Digital Tickets",
                "db_table": "digital_tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=255)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Template"),
                            ("email", "Email Template"),
                            ("mobile", "Mobile Template"),
                        ],
                        default="pdf",
                        help_text="Type of template",
                        max_length=10,
                    ),
                ),
                (
                    "html_content",
                    models.TextField(
                        help_text="HTML template content with placeholders"
                    ),
                ),
                (
                    "css_styles",
                    models.TextField(
                        blank=True, help_text="CSS styles for the template"
                    ),
                ),
                (
                    "page_size",
                    models.CharField(
                        choices=[
                            ("A4", "A4"),
                            ("Letter", "Letter"),
                            ("A5", "A5"),
                            ("Custom", "Custom"),
                        ],
                        default="A4",
                        help_text="Page size for PDF templates",
                        max_length=10,
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("portrait", "Portrait"), ("landscape", "Landscape")],
                        default="portrait",
                        help_text="Page orientation",
                        max_length=10,
                    ),
                ),
                (
                    "include_qr_code",
                    models.BooleanField(
                        default=True, help_text="Include QR code in template"
                    ),
                ),
                (
                    "include_barcode",
                    models.BooleanField(
                        default=False, help_text="Include barcode in template"
                    ),
                ),
                (
                    "include_logo",
                    models.BooleanField(
                        default=True, help_text="Include tenant logo in template"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether template is active"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default template for the tenant",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Template",
                "verbose_name_plural": "Ticket Templates",
                "db_table": "ticket_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TicketValidationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "validation_system_id",
                    models.CharField(
                        help_text="ID of the system that performed validation",
                        max_length=255,
                    ),
                ),
                (
                    "validation_result",
                    models.BooleanField(help_text="Whether validation was successful"),
                ),
                (
                    "validation_method",
                    models.CharField(
                        choices=[
                            ("qr_code", "QR Code Scan"),
                            ("ticket_number", "Ticket Number Entry"),
                            ("manual", "Manual Validation"),
                        ],
                        default="qr_code",
                        help_text="Method used for validation",
                        max_length=50,
                    ),
                ),
                (
                    "usage_count_before",
                    models.PositiveIntegerField(
                        default=0, help_text="Usage count before this validation"
                    ),
                ),
                (
                    "usage_count_after",
                    models.PositiveIntegerField(
                        default=0, help_text="Usage count after this validation"
                    ),
                ),
                (
                    "validation_location",
                    models.CharField(
                        blank=True,
                        help_text="Location where validation occurred",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of validation system",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent of validation system"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional validation metadata",
                    ),
                ),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="Ticket that was validated",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_logs",
                        to="tickets.digitalticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Validation Log",
                "verbose_name_plural": "Ticket Validation Logs",
                "db_table": "ticket_validation_logs",
                "ordering": ["-validated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="digitalticket",
            index=models.Index(
                fields=["tenant", "event", "status"],
                name="digital_tic_tenant__62fc12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="digitalticket",
            index=models.Index(
                fields=["tenant", "customer"], name="digital_tic_tenant__e99adf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalticket",
            index=models.Index(
                fields=["ticket_number"], name="digital_tic_ticket__7bee35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalticket",
            index=models.Index(
                fields=["validation_hash"], name="digital_tic_validat_1d341b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalticket",
            index=models.Index(
                fields=["transaction"], name="digital_tic_transac_909bd8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tickettemplate",
            unique_together={("tenant", "name", "template_type")},
        ),
        migrations.AddIndex(
            model_name="ticketvalidationlog",
            index=models.Index(
                fields=["tenant", "ticket", "validated_at"],
                name="ticket_vali_tenant__b8f903_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketvalidationlog",
            index=models.Index(
                fields=["validation_system_id"], name="ticket_vali_validat_3c1e0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketvalidationlog",
            index=models.Index(
                fields=["validation_result"], name="ticket_vali_validat_a8f8fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketvalidationlog",
            index=models.Index(
                fields=["validated_at"], name="ticket_vali_validat_ce61d1_idx"
            ),
        ),
    ]
