# Generated by Django 5.0.14 on 2025-10-31 03:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("sales", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("pago_movil", "Pago Móvil"),
                            ("zelle", "Zelle"),
                            ("paypal", "PayPal"),
                            ("other", "Other"),
                        ],
                        help_text="Type of payment method",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this payment method", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the payment method"
                    ),
                ),
                (
                    "requires_reference",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this method requires a reference number",
                    ),
                ),
                (
                    "allows_partial",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this method allows partial payments",
                    ),
                ),
                (
                    "processing_fee_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Processing fee as percentage (e.g., 0.0300 for 3%)",
                        max_digits=5,
                    ),
                ),
                (
                    "processing_fee_fixed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed processing fee amount",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this payment method is active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order for this payment method"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional configuration data (API keys, account info, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "payment_methods",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("installment", "Installment Plan"),
                            ("flexible", "Flexible Payment"),
                        ],
                        help_text="Type of payment plan",
                        max_length=15,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount to be paid",
                        max_digits=10,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount already paid",
                        max_digits=10,
                    ),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining balance to be paid",
                        max_digits=10,
                    ),
                ),
                (
                    "installment_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of installments (for installment plans)",
                        null=True,
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount per installment (for installment plans)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this payment plan expires"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When payment plan was completed",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        help_text="Current payment plan status",
                        max_length=10,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional plan configuration (due dates, reminders, etc.)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the payment plan"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who owns this payment plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_plans",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        help_text="Transaction this payment plan is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plan",
                        to="sales.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Plan",
                "verbose_name_plural": "Payment Plans",
                "db_table": "payment_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Payment amount", max_digits=10
                    ),
                ),
                (
                    "processing_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Processing fee charged",
                        max_digits=10,
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net amount after processing fees",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Payment currency", max_length=3
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Exchange rate used",
                        max_digits=10,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="External reference number (bank ref, card auth, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="External transaction ID from payment processor",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="Current payment status",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was processed", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was completed", null=True
                    ),
                ),
                (
                    "processor_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Response data from payment processor",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment metadata",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional payment notes"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="Transaction this payment is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sales.transaction",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        help_text="Payment method used",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "payment_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Payment plan this payment belongs to (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="payments.paymentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reconciliation_date",
                    models.DateField(help_text="Date of reconciliation"),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(help_text="Start of reconciliation period"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(help_text="End of reconciliation period"),
                ),
                (
                    "system_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount according to system records",
                        max_digits=12,
                    ),
                ),
                (
                    "external_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total amount according to external records (bank, processor)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "discrepancy_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Difference between system and external totals",
                        max_digits=12,
                    ),
                ),
                (
                    "system_transaction_count",
                    models.PositiveIntegerField(
                        help_text="Number of transactions in system"
                    ),
                ),
                (
                    "external_transaction_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of transactions in external records",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("discrepancy", "Discrepancy Found"),
                        ],
                        default="pending",
                        help_text="Reconciliation status",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When reconciliation was completed",
                        null=True,
                    ),
                ),
                (
                    "reconciliation_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed reconciliation data and findings",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Reconciliation notes and comments"
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        help_text="Payment method being reconciled",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Reconciliation",
                "verbose_name_plural": "Payment Reconciliations",
                "db_table": "payment_reconciliations",
                "ordering": ["-reconciliation_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["tenant", "is_active"], name="payment_met_tenant__d3d975_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["method_type"], name="payment_met_method__c0df5d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("tenant", "method_type", "name")},
        ),
        migrations.AddIndex(
            model_name="paymentplan",
            index=models.Index(
                fields=["tenant", "status"], name="payment_pla_tenant__68deb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentplan",
            index=models.Index(
                fields=["transaction"], name="payment_pla_transac_35278b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentplan",
            index=models.Index(
                fields=["customer"], name="payment_pla_custome_cc7549_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentplan",
            index=models.Index(
                fields=["expires_at"], name="payment_pla_expires_e98fbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "status"], name="payments_tenant__c38e7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction"], name="payments_transac_a1f824_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_method"], name="payments_payment_d03ee0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_plan"], name="payments_payment_a20aae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["reference_number"], name="payments_referen_a186d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["external_transaction_id"], name="payments_externa_c63e06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="payments_created_e3a130_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["tenant", "reconciliation_date"],
                name="payment_rec_tenant__946e7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["payment_method", "status"],
                name="payment_rec_payment_3a3cde_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(fields=["status"], name="payment_rec_status_ccdb77_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="paymentreconciliation",
            unique_together={("tenant", "payment_method", "reconciliation_date")},
        ),
    ]
