# Generated by Django 5.0.14 on 2025-11-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["is_active"], name="tenants_is_acti_ec1713_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["created_at"], name="tenants_created_fc84fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(
                fields=["user", "tenant"], name="tenant_user_user_id_6c8fb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(
                fields=["tenant", "role"], name="tenant_user_tenant__24f612_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(
                fields=["is_active"], name="tenant_user_is_acti_a9afac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["tenant", "role"], name="users_tenant__b30c7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["tenant", "is_active"], name="users_tenant__2f74ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
    ]
